### PR TITLE
feat: Added audit cronjob

### PR DESCRIPTION
**Pull request by isha689**
# Fixes [DII-528](https://issues.corp.twilio.com/browse/DII-528)

A short description of what this PR does.
Created cronjob which runs every night to check NPM audit vulnerabilities and send an alert in case of open vulnerabilities.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-cli-core/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by shrutiburman** [comment]
Would we also need this setup in twilio-cli's Audit check [workflow](https://github.com/twilio/twilio-cli/actions/workflows/cli-audit.yml)? 
Also, please link a successful run to verify the change.

**Comment by isha689** [comment]
Link for change verification : https://github.com/isha689/twilio-cli-core/actions
 
Screenshot 2022-08-01 at 8 27 43 PM

**Review by shrutiburman — APPROVED** [review]
LGTM! 👏 🚀

**Comment by shrutiburman** [comment]
> Would we also need this setup in twilio-cli's Audit check [workflow](https://github.com/twilio/twilio-cli/actions/workflows/cli-audit.yml)? Also, please link a successful run to verify the change.

Lets see if we need this in twilio-cli too ?

**Review by shrutiburman — APPROVED** [review]

**Pull request closed without merging**
