### PR TITLE
feat:  Added support to make profile input mandatory based on config property

### PR DESCRIPTION
**Pull request by kridai**
# Fixes #
Closed : DI-424

Added support to make profile input mandatory based on config property. Introduced a new flag to be stored in config.

Testing Gist: [Link](https://gist.github.com/kridai/72e5962a40834815d5b8f79579112c93)

Screenshot

Screenshot 2021-07-27 at 10 27 13 AM

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-cli-core/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Review by onuzbee — APPROVED** [review]
👍🏻

**Review by ravali-rimmalapudi — COMMENTED** [review]
Looks Good.

**Comment by shamantraghav** [comment]
Looks good!

**Review by shamantraghav — APPROVED** [review]

**Review by shrutiburman — APPROVED** [review]
🚀

**Pull request merged**
